apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 374606205328.dkr.ecr.us-east-1.amazonaws.com/my-frontend-app:d4c6bafa6859749c621e8e9d325bfad0d21be18e
          ports:
            - containerPort: 3000
