name: 3. CI Workflow - Backend End Config

on:
  push:
    branches:
      - main
    paths:
      - 'starter/backend/**'  # Trigger only if code in the backend folder changes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd frontend
          npm install
      - name: Run eslint
        run: |
          cd frontend
          npm run lint

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [lint]
    if: ${{ needs.lint.result == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          cd backend
          docker build -t my-backend-app:${{ github.sha }} -f starter/backend/Dockerfile .
