name: 3. CI Workflow - Backend End Config

on:
  pull_request:
    branches:
      - main  # Trigger on PRs to the main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd frontend
          npm install
      - name: Run eslint
        run: |
          cd frontend
          npm run lint
          
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd frontend
          npm install
      - name: Run tests
        run: |
          cd frontend
          npm test

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: ${{ needs.lint.result == 'success' && needs.test.result == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker image
        run: |
          cd backend
          docker build -t my-backend-app:${{ github.sha }} -f starter/backend/Dockerfile .

