name: 3. CI Workflow - Backend End Config

on:
  pull_request:
    branches:
      - main  # Trigger on PRs to the main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Set the Python version for linting

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r starter/backend/requirements.txt  # Assuming a requirements.txt file exists

      # - name: Run Linting
      #   run: |
      #     pylint .  # Or your preferred linting tool
          
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint  # Ensures linting job completes first
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Set the Python version for tests

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r starter/backend/requirements.txt  # Assuming a requirements.txt file exists

      - name: Run Tests
        run: |
          pytest  # Or your preferred testing tool

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [lint, test]  # Ensures linting and testing jobs complete before build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-backend-app -f starter/backend/Dockerfile .

      # - name: Push Docker image (Optional)
      #   run: |
      #     docker push my-backend-app  # Push the built image to your Docker registry

