name: 3. CI Workflow - Backend End Config

on:
  pull_request:
    branches:
      - main
    paths:
      - 'starter/backend/**'
  workflow_dispatch:

jobs:
  test:
    name: Run Backend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pipenv
        run: pip install pipenv
        working-directory: starter/backend

      - name: Install dependencies
        run: |
          cd starter/backend
          pipenv install
        working-directory: starter/backend

      - name: Run tests
        run: |
          cd starter/backend
          pipenv run test
        working-directory: starter/backend

  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install pipenv
        run: pip install pipenv
        working-directory: starter/backend

      - name: Install dependencies
        run: |
          pipenv install
        working-directory: starter/backend

      - name: Run linter
        run: |
          pipenv run lint
        working-directory: starter/backend

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker image
        run: |
          docker build --tag my-backend-app:latest .
        working-directory: starter/backend
